web: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
susnpot: rake sunspot:solr:run
queue: bundle exec sidekiq -C config/sidekiq.yml
sidekiq_web: bundle exec thin -R sidekiq.ru start -p 3001
